### ISSUE TITLE
NoMethodError: undefined method `[]=' for nil:NilClass in specs

### ISSUE THREAD

**Issue by mdegoys** [BaseSecrete/rorvswild#18]
Hello,
after installing the gem, I have these errors `NoMethodError: undefined method []= for nil:NilClass`on almost all my tests using rspec (for every route requests actually). The app runs fine though.

I'm using ruby 2.7.2p137, Rails 6.1.3, and rorvswild 1.5.9.

Do you know what could be the issue here ?
Many thanks,
Matthieu

**Comment by alexisbernard** [comment]
Hello, I tried to setup an app with the versions you mentioned (https://github.com/alexisbernard/rorvswild-issue18) but I didn't succeed to reproduce the error. Are you able to create a minimal app or do you have at least the backtrace ?

**Comment by mdegoys** [comment]
Thanks for your answer - I could have the same error by adding the rorvswild initializer and a controller spec. I made a pull request on the repo you created if you want to look at it. Maybe there is something I'm doing wrong ?

**Comment by alexisbernard** [comment]
Thanks very much for the PR. I reproduced and fixed the error. Can you run your entire spec with this specific version and tell me there is no errors ?

```
gem 'rorvswild', git: 'https://github.com/BaseSecrete/rorvswild.git', ref: '1ccb5c8fdaa8bf16a44fae26e16051b3251a6edd
```

> Edit: It seems that if I don't use the initializer (but the yml config file instead) I can run the specs.

I suppose rorvswild.yml contains the API key for the production environment only. Whereas rorvswild.rb initializes for all environments. Maybe you should add `if ENV["RORVSWILD_API_KEY"]` before the initialization since there is no needs in tracking performances and errors in test environment.

**Comment by mdegoys** [comment]
Hello, thanks for the quick reply and fix. Yes I can confirm I can run the specs for my app. 

I didn't know about the difference between the initializer and the yml files. I guess I'll stick with the yml for now :).
